### ISSUE TITLE
微信小程序使用多态组件storage报错

### ISSUE THREAD

**Issue by zjdgx** [didi/chameleon#105]
**bug描述**
微信小程序使用[多态组件storage(官网上复制)](https://cmljs.org/doc/example/poly.html)在编译时报错:
```
 ERROR  Failed to compile with 1 errors                                                                                                               21:41:04

 error  in ./src/components/utils/utils.interface

Syntax Error: Unexpected character ' (15:13)

  13 |
  14 | // web 接口实现
> 15 | class Methodimplements UtilsInterface {
     |              ^
  16 |   setStorage(key, value, cb) {
  17 |     try {
  18 |       localStorage.setItem(key, value);



 @ /usr/local/lib/node_modules/chameleon-tool/node_modules/babel-loader/lib?{"filename":"/usr/local/lib/node_modules/chameleon-tool/chameleon.js"}!/usr/local/lib/node_modules/chameleon-tool/node_modules/vue-loader/lib/selector.js?type=script&index=0!/usr/local/lib/node_modules/chameleon-tool/node_modules/chameleon-loader/src??ref--12-1!./src/pages/todo/index.cml 27:13-62
 @ ./src/pages/todo/index.cml
 @ ./node_modules/chameleon-runtime/.temp/router.js
 @ ./node_modules/chameleon-runtime/.temp/entry.js
 @ multi /usr/local/lib/node_modules/chameleon-tool/commanders/web/liveload-dev-client.js ./node_modules/chameleon-runtime/.temp/entry.js
```

微信开发者工具中报错
```
VM6001:1 thirdScriptError 
 sdk uncaught third Error 
 Module build failed: SyntaxError: Unexpected character '' (15:13)

[0m [90m 13 | [39m    
 [90m 14 | [39m[90m// wx端接口实现[39m
[31m[1m>[22m[39m[90m 15 | [39m[36mclass[39m [33mMethod[39m [37m[41m[1m[22m[49m[39mimplements [33mUtilsInterface[39m {
 [90m    | [39m             [31m[1m^[22m[39m
 [90m 16 | [39m  setStorage(key[33m,[39m value[33m,[39m cb) {
 [90m 17 | [39m    [37m[41m[1m[22m[49m[39m[36mtry[39m {
 [90m 18 | [39m      wx[33m.[39msetStorageSync(key[33m,[39m value)[33m;[39m[0m
 
 Error: Module build failed: SyntaxError: Unexpected character '' (15:13)

[0m [90m 13 | [39m    
 [90m 14 | [39m[90m// wx端接口实现[39m
[31m[1m>[22m[39m[90m 15 | [39m[36mclass[39m [33mMethod[39m [37m[41m[1m[22m[49m[39mimplements [33mUtilsInterface[39m {
 [90m    | [39m             [31m[1m^[22m[39m
 [90m 16 | [39m  setStorage(key[33m,[39m value[33m,[39m cb) {
 [90m 17 | [39m    [37m[41m[1m[22m[49m[39m[36mtry[39m {
 [90m 18 | [39m      wx[33m.[39msetStorageSync(key[33m,[39m value)[33m;[39m[0m

    at Object.srcComponentsUtilsUtilsInterface (http://127.0.0.1:14923/appservice/static/js/pages/todo/index.js:110:11)
    at __webpack_require__ (http://127.0.0.1:14923/appservice/static/js/manifest.js:72:31)
    at Object.usrLocalLibNo......
```

**编译环境信息**
 - chameleon-tool 版本：[0.0.16]
 - nodejs版本、npm版本：[node v9.0.0、npm 5.5.1]
 - 电脑操作系统： [e.g. macOS X EI Capitan 10.11.6]

**运行环境信息**
 - 端版本：[微信开发者工具1.02.1902010]
 - 手机机型: [iPhone6 12.0]

**Comment by AdamEleven** [comment]
13 |
  14 | // web 接口实现
> 15 | class Methodimplements UtilsInterface {
     |              ^
  16 |   setStorage(key, value, cb) {
  17 |     try {
  18 |       localStorage.setItem(key, value);

看起来第15行代码Method   implements 中间缺了一个空格, 这个是从文档哪里复制的? 我们定位一下问题, 方便修改

**Comment by zjdgx** [comment]
代码是从这里复制的 https://cmljs.org/doc/framework/polymorphism/api.html
这个问题还需要验证一下
我`cml init project`创建项目后再用`cml init component`创建的组件是 **[多个]** 文件了
旧项目中`cml init component`创建的组件只有 **[一个]** 文件

**Comment by AdamEleven** [comment]
那个报错的问题, 我这边看了下文档demo, 应该是没有同样错误的, 你再确认一下?
另一个问题能否提供一下具体示例

**Comment by beatles-chameleon** [comment]
那个报错的问题, 我这边看了下文档demo, 应该是没有同样错误的, 你再确认一下?
另一个问题能否提供一下具体示例

**Comment by NextBoy** [comment]
这么明显的错误看不出？
```
class Methodimplements UtilsInterface
```
少了个空格, 应该改为
```
class Method implements UtilsInterface
```
