### ISSUE TITLE
微信小程序分包编译报错

### ISSUE THREAD

**Issue by TheLostlyp** [didi/chameleon#265]
调试了下，猜测是miniAppSubPkg.js里的subPageJSPath和subPageStaticJSPath使用了\反斜线的问题；
系统：windows
subPageJSPath打印是：packages\search\pages\search\search.js
然而在compilation.assets里是：packages/search/pages/search/search.js
导致编译中断

**Comment by Bowen7** [comment]
请回复一下app.cml的json配置，pages的目录结构，chameleon-tool 版本号，window 系统版本号。以及报错提示信息。

pages 目录结构需要 app.cml json 配置中 subPackages 使用到的页面的  路径信息。

**Comment by TheLostlyp** [comment]
app.cml的json配置（分包配置比较多，精简到一个分包的配置也会编译报错并中断）：
```json
{  
  "base": {  
    "usingComponents": {  
    }  
  },  
  "wx": {  
    "window": {  
      "navigationBarBackgroundColor": "#FAFAFA",  
      "navigationBarTextStyle": "black",  
      "backgroundColor": "#FAFAFA",  
      "onReachBottomDistance": 1000,  
      "navigationStyle": "custom"  
    },  
    "networkTimeout": {  
      "request": 15000,  
      "downloadFile": 15000  
    },  
    "subPackages": [  
      {  
        "root": "packages/account",  
        "pages": [  
          "pages/conflict/conflict",  
          "pages/login/login",  
          "pages/update/update",  
          "pages/updatemobile/updatemobile",  
          "pages/updatename/updatename",  
          "pages/validMobile/validMobile",  
          "pages/webBindMobile/webBindMobile"  
        ]  
      }  
    ]  
  }  
}  
```
pages的目录结构：
![image](https://user-images.githubusercontent.com/33479477/63495817-2cd89800-c4f3-11e9-9620-50e47dabd149.png)
chameleon-tool版本号：0.4.0
window版本号：win 10
node版本号：v8.12.0
npm版本号：6.4.1
运行报错：
```
(node:14132) UnhandledPromiseRejectionWarning: TypeError: Cannot set property '_value' of undefined
    at subPagesArr.forEach (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\configs\plugins\miniAppSubPkg.js:61:50)
    at Array.forEach (<anonymous>)
    at Compiler.miniappsubpkg (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\configs\plugins\miniAppSubPkg.js:46:19)
    at next (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\node_modules\webpack\node_modules\tapable\lib\Tapable.js:204:14)
    at Compiler.checkModule (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\node_modules\webpack-check-plugin\index.js:75:14)
    at Compiler.applyPluginsAsyncSeries (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\node_modules\webpack\node_modules\tapable\lib\Tapable.js:206:13)
    at Compiler.emitAssets (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\node_modules\webpack\lib\Compiler.js:354:8)
    at onCompiled (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\node_modules\webpack\lib\Compiler.js:58:19)
    at applyPluginsAsync.err (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\node_modules\webpack\lib\Compiler.js:510:14)
    at next (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\node_modules\webpack\node_modules\tapable\lib\Tapable.js:202:11)
    at Compiler.<anonymous> (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\node_modules\webpack\lib\CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\node_modules\webpack\node_modules\tapable\lib\Tapable.js:206:13)
    at compilation.seal.err (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\node_modules\webpack\lib\Compiler.js:507:11)
    at Compilation.applyPluginsAsyncSeries (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\node_modules\webpack\node_modules\tapable\lib\Tapable.js:195:46)
    at applyPluginsAsync.err (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\node_modules\webpack\lib\Compilation.js:683:19)
    at Compilation.applyPluginsAsyncSeries (C:\Users\lyp\AppData\Roaming\npm\node_modules\chameleon-tool\node_modules\webpack\node_modules\tapable\lib\Tapable.js:195:46)
(node:14132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not
handled with .catch(). (rejection id: 1)
(node:14132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jimwmg** [comment]
npm i chameleon-tool@0.4.1-alpha.1 -g
