### ISSUE TITLE
cml dev 报错 TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by eeve** [didi/chameleon#304]
**bug描述**

运行`cml dev -n`命令报错，内容如下

```bash
$ cml dev -n

[INFO] start Compiling...

[INFO] wx Compiling...



[INFO] wx Compiled successfully in 11048ms

[INFO] Listening at http://192.168.1.57:8000/preview.html
(node:15175) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at issues.concat.issueAttrs.map (/Users/eeve/.nvm/versions/node/v10.16.0/lib/node_modules/chameleon-tool/node_modules/cml-htmllint/lib/rules/component-attr-check.js:111:153)
    at Array.map (<anonymous>)
    at Object.module.exports.lint (/Users/eeve/.nvm/versions/node/v10.16.0/lib/node_modules/chameleon-tool/node_modules/cml-htmllint/lib/rules/component-attr-check.js:109:50)
    at /Users/eeve/.nvm/versions/node/v10.16.0/lib/node_modules/chameleon-tool/node_modules/cml-htmllint/lib/knife/apply_rules.js:62:36
    at Array.map (<anonymous>)
    at Object.applyRules (/Users/eeve/.nvm/versions/node/v10.16.0/lib/node_modules/chameleon-tool/node_modules/cml-htmllint/lib/knife/apply_rules.js:58:41)
    at Object.module.exports.lint (/Users/eeve/.nvm/versions/node/v10.16.0/lib/node_modules/chameleon-tool/node_modules/cml-htmllint/lib/rules/tag.js:14:18)
    at /Users/eeve/.nvm/versions/node/v10.16.0/lib/node_modules/chameleon-tool/node_modules/cml-htmllint/lib/knife/apply_rules.js:62:36
    at Array.map (<anonymous>)
    at Object.applyRules (/Users/eeve/.nvm/versions/node/v10.16.0/lib/node_modules/chameleon-tool/node_modules/cml-htmllint/lib/knife/apply_rules.js:58:41)
    at getIssues (/Users/eeve/.nvm/versions/node/v10.16.0/lib/node_modules/chameleon-tool/node_modules/cml-htmllint/lib/rules/dom.js:24:25)
    at /Users/eeve/.nvm/versions/node/v10.16.0/lib/node_modules/chameleon-tool/node_modules/cml-htmllint/lib/rules/dom.js:28:34
    at Array.forEach (<anonymous>)
    at getIssues (/Users/eeve/.nvm/versions/node/v10.16.0/lib/node_modules/chameleon-tool/node_modules/cml-htmllint/lib/rules/dom.js:27:30)
    at /Users/eeve/.nvm/versions/node/v10.16.0/lib/node_modules/chameleon-tool/node_modules/cml-htmllint/lib/rules/dom.js:28:34
    at Array.forEach (<anonymous>)
(node:14954) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:14954) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

根据报错信息在 [https://github.com/didi/chameleon/blob/v1.0.3/packages/cml-htmllinter/lib/rules/component-attr-check.js#L110](https://github.com/didi/chameleon/blob/v1.0.3/packages/cml-htmllinter/lib/rules/component-attr-check.js#L110) 第110行上方加入代码：

```js
console.log(111, eventRegex)
console.log(222, eventRegex.exec(issueAttr.name))
console.log(333, issueAttr)
```

重新执行 `cml dev -n` 命令，打印内容如下：
```bash
111 /(?:v-on:|v-once:|@)(\w+)/
222 null
333 { value: '(url, index) in goods.pics',
  nameIndex: 265,
  rawEqValue: '=\'(url, index) in goods.pics\'',
  rawValue: '\'(url, index) in goods.pics\'',
  valueIndex: 271,
  nameLineCol: [ 5, 24 ],
  valueLineCol: [ 5, 30 ],
  name: 'v-for',
  _isEvent: false }
```

初步判定问题所在，第110行代码中未处理 `eventRegex.exec(issueAttr.name)` 为 `null` 的情况：
```
eventRegex.exec(issueAttr.name)[1]
```

**复现bug的步骤**

**问题截图**
<img width="1435" alt="111" src="https://user-images.githubusercontent.com/16770728/66538576-979f6a80-eb57-11e9-8bce-827f2a05a589.png">

**编译环境信息**
 - chameleon-tool 版本：1.0.3
 - nodejs版本、npm版本：[node v10.16.0、npm 6.9.0]
 - 电脑操作系统： [macOS Mojave 10.14]

**Comment by beatles-chameleon** [comment]
感谢反馈！让相关同学跟进下~
