### ISSUE TITLE
cml.getSystemInfo()报错

### ISSUE THREAD

**Issue by xztl** [didi/chameleon#375]
**bug描述**
描述出现的问题
in ./node_modules/chameleon-api/src/interfaces/getSystemInfo/index.interface

Module build failed: Error: not find <script cml-type='quickapp'></script> in /Users/chester1/Desktop/jiuwen-cml-quickapp/node_modules/chameleon-api/src
/interfaces/getSystemInfo/index.interface
    at getRawContent (/usr/local/lib/node_modules/chameleon-tool/node_modules/mvvm-interface-parser/lib/getMethodCode.js:79:13)
    at module.exports (/usr/local/lib/node_modules/chameleon-tool/node_modules/mvvm-interface-parser/lib/getMethodCode.js:83:48)
    at module.exports (/usr/local/lib/node_modules/chameleon-tool/node_modules/mvvm-interface-parser/index.js:11:22)
    at Object.module.exports (/usr/local/lib/node_modules/chameleon-tool/node_modules/interface-loader/src/index.js:11:27)

 @ ./node_modules/chameleon-api/src/interfaces/getSystemInfo/index.js 9:13-41
 @ /usr/local/lib/node_modules/chameleon-tool/node_modules/babel-loader/lib?{"filename":"/usr/local/lib/node_modules/chameleon-tool/chameleon.js"}!/usr/
local/lib/node_modules/chameleon-tool/configs/mvvm/originSourceLoader.js!/usr/local/lib/node_modules/chameleon-tool/node_modules/mvvm-cml-loader/selecto
r.js?{"cmlType":"quickapp","media":"dev","check":{"enable":true,"enableTypes":[]},"fileType":"page","partType":"script"}!./src/pages/index/index.cml
 @ ./src/pages/index/index.cml
 @ ./src/app/app.cml

**复现bug的步骤**
编译报错

**问题截图**
![image](https://user-images.githubusercontent.com/11171790/75600069-f5702700-5ae5-11ea-93d2-78b453fde6e2.png)

**编译环境信息**
 - chameleon-tool 版本：1.0.4
 - nodejs版本、npm版本：node v12.13.1、npm 6.13.7
 - 电脑操作系统： macOS Catania 10.15.3

**运行环境信息**
 - 端版本： 快应用开发，无法成功编译快应用代码
 - 手机机型: 无

**Comment by jimwmg** [comment]
这个哪个案例？

**Comment by xztl** [comment]
抱歉，我没有正确导入cml快应用api导致
