### ISSUE TITLE
Module build failed: Error

### ISSUE THREAD

**Issue by smwsk** [didi/chameleon#75]
**bug描述**
描述出现的问题

**复现bug的步骤**
1. cml 创建项目
2. cml dev

**问题截图**
 error  in ./src/app/app.cml

Module build failed: Error:

Vue packages version mismatch:

- vue@2.5.16
- vue-template-compiler@2.6.8

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (D:\Study\NodeJs\node8\node_global\node_modules\chameleon-tool\node_modules\_vue-template-compiler@2.6.8@vue-template-compiler\index.js:8:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Study\NodeJs\node8\node_global\node_modules\chameleon-tool\node_modules\_chameleon-weex-vue-loader@0.0.16-alpha.0@chameleon-weex-vue-loader\lib\parser.js:2:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

 @ ./node_modules/chameleon-runtime/.temp/entry.js 5:11-46
 @ multi ./node_modules/chameleon-runtime/.temp/entry.js D:/Study/NodeJs/node8/node_global/node_modules/chameleon-tool/configs/weex_liveload/liveLoad.js

 error  in ./src/pages/index/index.cml

Module build failed: Error:

Vue packages version mismatch:

- vue@2.5.16
- vue-template-compiler@2.6.8

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (D:\Study\NodeJs\node8\node_global\node_modules\chameleon-tool\node_modules\_vue-template-compiler@2.6.8@vue-template-compiler\index.js:8:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Study\NodeJs\node8\node_global\node_modules\chameleon-tool\node_modules\_chameleon-weex-vue-loader@0.0.16-alpha.0@chameleon-weex-vue-loader\lib\parser.js:2:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

 @ ./node_modules/chameleon-runtime/.temp/router.js 24:19-64
 @ ./node_modules/chameleon-runtime/.temp/entry.js
 @ multi ./node_modules/chameleon-runtime/.temp/entry.js D:/Study/NodeJs/node8/node_global/node_modules/chameleon-tool/configs/weex_liveload/liveLoad.js

**编译环境信息**
 - chameleon-tool 版本：[0.0.16]
 - nodejs版本、npm版本：[node v8.11.3、npm 6.8.0]
 - 电脑操作系统： [e.g. macOS High Sierra 10.13.6]

**运行环境信息**
 - 端版本： [e.g. 微信小程序 7.0.3、weex 2.0、手机Safari浏览器 、PC Chrome浏览器 1.30]
 - 手机机型: [e.g. iPhone6 12.0]

**Comment by beatles-chameleon** [comment]
删除 D:\Study\NodeJs\node8\node_global\node_modules\chameleon-tool目录，利用npm 安装chameleon-tool，不支持使用yarn或cnpm安装

**Comment by smwsk** [comment]
我用的是cnpm安装的，但是我换npm安装的时候会报问题，
npm ERR! path D:\Study\NodeJs\node8\node_global\node_modules\.staging\jison-gho-30e29417\.nyc_output\cd45154552a79ebb3dd6f3f06c489177.json                                                                                                      npm ERR! code EPERM
npm ERR! errno -4048                                                                                                    npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\Study\NodeJs\node8\node_global\node_modules\.staging\jison-gho-30e29417\.nyc_output\cd45154552a79ebb3dd6f3f06c489177.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'D:\Study\NodeJs\node8\node_global\node_modules\.staging\jison-gho-30e29417\.nyc_output\cd45154552a79ebb3dd6f3f06c489177.json'                                                        npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'D:\Study\NodeJs\node8\node_global\node_modules\.staging\jison-gho-30e29417\.nyc_output\cd45154552a79ebb3dd6f3f06c489177.json'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'D:\\Study\\NodeJs\\node8\\node_global\\node_modules\\.staging\\jison-gho-30e29417\\.nyc_output\\cd45154552a79ebb3dd6f3f06c489177.json' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'D:\\Study\\NodeJs\\node8\\node_global\\node_modules\\.staging\\jison-gho-30e29417\\.nyc_output\\cd45154552a79ebb3dd6f3f06c489177.json\'',
npm ERR!   errno: -4048,                                                                                                npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',                                                                                           npm ERR!   path: 'D:\\Study\\NodeJs\\node8\\node_global\\node_modules\\.staging\\jison-gho-30e29417\\.nyc_output\\cd45154552a79ebb3dd6f3f06c489177.json',                                                                                       npm ERR!   parent: 'chameleon-tool' }
npm ERR!                                                                                                                npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),                                npm ERR! or that you lack permissions to access it.
npm ERR!                                                                                                                npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running                                         npm ERR! the command again as root/Administrator (though this is not recommended).
                                                                                                                        npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Study\NodeJs\node8\node_cache\_logs\2019-03-11T02_00_23_025Z-debug.log

**Comment by beatles-chameleon** [comment]
你的报错是删除权限的问题，建议删除 D:\Study\NodeJs\node8\node_global\node_modules 下的所有内容再用npm安装。也可以搜索解决方案，例如： http://www.mamicode.com/info-detail-1495419.html
